# DB 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://whiskeywiki.shop:3306/whiskeywikiDB?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: b101

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none